server:
  port: 8080

spring:
  application:
    name: rest-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: orders
    password: orders
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

email-service:
  base-url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
